name: 4000Ada_unet_cuda
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.26.4
  - scipy=1.11.4
  - pandas=2.2.3
  - scikit-learn=1.3.2
  - matplotlib=3.8.0
  - tqdm
  - xarray
  - netcdf4
  - h5py
  - h5netcdf
  - dask
  - pip
  - pip:
    - --index-url https://download.pytorch.org/whl/cu121
    - torch==2.2.0
    - torchvision==0.17.0
    - opencv-python==4.10.0.84
    - opencv-python-headless==4.10.0.84
    - tifffile==2024.2.12
    - einops==0.6.1
    - albumentations==1.3.1
    - segmentation-models-pytorch==0.3.3
    - imageio==2.34.0
    - thop==0.1.1.post2209072238
    - timm==0.9.2
    - torch-harmonics==0.6.5